# Generated by Django 3.2.7 on 2021-09-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20210921_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(default='Categoria', max_length=100),
        ),
    ]
