# Generated by Django 3.2.7 on 2021-09-22 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20210921_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='category_name',
            new_name='name',
        ),
    ]
